import { defineConfig } from 'vite';
import { existsSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';

// Multi-page static site: the home plus one page per case in work/<slug>/,
// generated by scripts/build-cases.ts before dev and build.
const root = import.meta.dirname;

const workDir = resolve(root, 'work');
const cases = existsSync(workDir) ? readdirSync(workDir) : [];

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        home: resolve(root, 'index.html'),
        ...Object.fromEntries(cases.map((slug) => [slug, resolve(workDir, slug, 'index.html')])),
      },
    },
  },
});
